allowBuilds:
    electron: true
    esbuild: true
    node-pty: true
    koffi: true
    simple-git-hooks: true
    protobufjs: true
    '@google/genai': false
    electron-winstaller: true
    sharp: true
minimumReleaseAge: 720
