const HOME = '/Users/dev';
const hoursAgo = (hours: number) => Date.now() - hours * 3_600_000;

export const FIXTURE_VIEWS = [
    {
        id: 'demo-checkout',
        title: 'Extract checkout totals',
        description: 'Totals moved into `lib/pricing` with the rounding rules covered by tests.',
        status: 'finished',
        cwd: `${HOME}/code/storefront`,
        sourceId: 'builtin:pi',
        sessionId: 'demo-session-checkout',
        model: 'pi-1',
        lockTitle: true,
        lastActiveAt: hoursAgo(0.03),
    },
    {
        id: 'demo-upload',
        title: 'Flaky upload test in CI',
        description: 'Should a failed thumbnail job retry, or fail the whole upload?',
        status: 'attention',
        cwd: `${HOME}/code/edge-api`,
        sourceId: 'builtin:claudecode',
        sessionId: 'demo-session-upload',
        model: 'claude-opus-5',
        lockTitle: true,
        lastActiveAt: hoursAgo(0.3),
    },
    {
        id: 'demo-ratelimit',
        title: 'Rate limit the search endpoint',
        description: 'Walking the handler chain to find where the token bucket belongs.',
        status: 'working',
        cwd: `${HOME}/code/edge-api`,
        sourceId: 'builtin:pi',
        sessionId: 'demo-session-ratelimit',
        model: 'pi-1',
        lockTitle: true,
        lastActiveAt: hoursAgo(1),
    },
    {
        id: 'demo-config',
        title: 'Config loading through a schema',
        description: 'All 19 environment reads now go through one validated config object.',
        status: 'finished',
        cwd: `${HOME}/code/storefront`,
        sourceId: 'builtin:claudecode',
        sessionId: 'demo-session-config',
        model: 'claude-opus-5',
        lockTitle: true,
        lastActiveAt: hoursAgo(3),
    },
    {
        id: 'demo-preview',
        title: 'Preview deploys for pull requests',
        description: 'Running `terraform plan` against the preview workspace to see what the PR would create.',
        status: 'working',
        cwd: `${HOME}/code/infra`,
        sourceId: 'builtin:pi',
        lockTitle: true,
        lastActiveAt: hoursAgo(6),
    },
    {
        id: 'demo-flags',
        title: 'Strip the dead feature flags',
        description: 'Removed 7 flags that have been fully rolled out since spring.',
        status: 'finished',
        cwd: `${HOME}/code/storefront`,
        sourceId: 'builtin:claudecode',
        sessionId: 'demo-session-flags',
        model: 'claude-opus-5',
        lockTitle: true,
        lastActiveAt: hoursAgo(11),
    },
    {
        id: 'demo-cache',
        title: 'Cache invalidation on product update',
        description: 'New Pi instance',
        status: 'idle',
        cwd: `${HOME}/code/edge-api`,
        sourceId: 'builtin:pi',
        lockTitle: true,
        lastActiveAt: hoursAgo(13),
    },
    {
        id: 'demo-drift',
        title: 'Terraform drift on the staging bucket',
        description: 'Plan wants to destroy the bucket — stopped before applying.',
        status: 'error',
        cwd: `${HOME}/code/infra`,
        sourceId: 'builtin:claudecode',
        sessionId: 'demo-session-drift',
        model: 'claude-opus-5',
        lockTitle: true,
        lastActiveAt: hoursAgo(16),
    },
    {
        id: 'demo-a11y',
        title: 'Accessibility pass on the cart drawer',
        description: 'Focus trap and labels fixed; the drawer now closes on Escape.',
        status: 'finished',
        cwd: `${HOME}/code/storefront`,
        sourceId: 'builtin:pi',
        sessionId: 'demo-session-a11y',
        model: 'pi-1',
        lockTitle: true,
        lastActiveAt: hoursAgo(20),
    },
    {
        id: 'demo-rebase',
        title: 'edge-api',
        description: 'git rebase --continue',
        status: 'idle',
        cwd: `${HOME}/code/edge-api`,
        sourceId: 'builtin:shell',
        lockTitle: true,
        lastActiveAt: hoursAgo(28),
    },
    {
        id: 'demo-node',
        title: 'Bump Node to 22 across CI',
        description: 'New Pi instance',
        status: 'idle',
        cwd: `${HOME}/code/infra`,
        sourceId: 'builtin:pi',
        lockTitle: true,
        lastActiveAt: hoursAgo(50),
    },
    {
        id: 'demo-shell',
        title: 'storefront',
        description: 'pnpm test --filter web',
        status: 'idle',
        cwd: `${HOME}/code/storefront`,
        sourceId: 'builtin:shell',
        lockTitle: true,
        lastActiveAt: hoursAgo(9),
    },
];

export const FIXTURE_WORKSPACES: Record<string, unknown> = {
    '': { cwd: `${HOME}/code/storefront`, icon: null, path: `${HOME}/code/storefront`, branch: 'main', isGit: true },
    [`${HOME}/code/storefront`]: {
        cwd: `${HOME}/code/storefront`,
        icon: null,
        path: `${HOME}/code/storefront`,
        branch: 'main',
        isGit: true,
    },
    [`${HOME}/code/edge-api`]: {
        cwd: `${HOME}/code/edge-api`,
        icon: null,
        path: `${HOME}/code/edge-api`,
        branch: 'main',
        isGit: true,
    },
    [`${HOME}/code/infra`]: {
        cwd: `${HOME}/code/infra`,
        icon: null,
        path: `${HOME}/code/infra`,
        branch: 'deploy-previews',
        isGit: true,
    },
};

const reset = '\x1b[0m';
const bold = (text: string) => `\x1b[1m${text}${reset}`;
const dim = (text: string) => `\x1b[2m${text}${reset}`;
const cyan = (text: string) => `\x1b[36m${text}${reset}`;
const green = (text: string) => `\x1b[32m${text}${reset}`;
const red = (text: string) => `\x1b[31m${text}${reset}`;
const yellow = (text: string) => `\x1b[33m${text}${reset}`;
const blue = (text: string) => `\x1b[34m${text}${reset}`;

export interface TranscriptChunk {
    text: string;
    delay: number;
}

function lines(...entries: string[]): TranscriptChunk[] {
    return entries.map((text) => ({ text: `${text}\r\n`, delay: 12 }));
}

const TRANSCRIPTS: Record<string, TranscriptChunk[]> = {
    'demo-checkout': lines(
        `  ${bold('Pull the checkout total maths out of the React tree so I can test it on its own.')}`,
        '',
        `  ${dim('Read')} ${cyan('app/checkout/summary.tsx')} ${dim('· 214 lines')}`,
        `  ${dim('Read')} ${cyan('app/checkout/use-cart.ts')} ${dim('· 96 lines')}`,
        '',
        '  The totals are computed in three places and they disagree about rounding, which is why',
        '  the tax line drifts by a cent on carts with a percentage discount. I moved all of it into',
        `  ${cyan('lib/pricing/totals.ts')} as pure functions over a cart, leaving the components to render what`,
        '  comes back.',
        '',
        `  ${dim('Edited')} ${cyan('lib/pricing/totals.ts')}  ${green('+128')} ${red('-0')}`,
        `  ${dim('Edited')} ${cyan('app/checkout/summary.tsx')}  ${green('+9')} ${red('-71')}`,
        `  ${dim('Edited')} ${cyan('app/checkout/use-cart.ts')}  ${green('+4')} ${red('-38')}`,
        '',
        `  ${green('+')} export function cartTotals(cart: Cart, rules: TaxRules): Totals {`,
        `  ${green('+')}     const subtotal = cart.lines.reduce((sum, line) => sum + line.unitCents * line.qty, 0);`,
        `  ${green('+')}     const tax = roundHalfEven(taxableBase(subtotal - discount, rules) * rules.rate);`,
        `  ${red('-')}     const tax = Math.round((subtotal - discount) * 0.2 * 100) / 100;`,
        '',
        `  ${dim('Ran')} ${cyan('pnpm vitest run lib/pricing')}`,
        `  ${green('✓')} totals.test.ts ${dim('(24 tests)')} ${dim('412ms')}`,
        `  ${green('✓')} discounts.test.ts ${dim('(11 tests)')} ${dim('189ms')}`,
        '',
        '  The cent drift is gone — the rounding is half-even now, matching what the payment provider',
        '  reports back. Two of those tests fail against the old code, so they pin the bug.',
        '',
        `  ${dim('Churned for 2m 14s · done 11:42')}`,
        '',
        `  ${bold('Good. Does anything else still do its own rounding?')}`,
        '',
        `  ${dim('Grep')} ${cyan('"Math.round"')} ${dim('· 2 matches outside lib/pricing')}`,
        '',
        `  Only the invoice PDF renderer, and it rounds for display after the totals are settled, so it`,
        `  cannot drift. The refund path already calls ${cyan('cartTotals')} — I pointed it at the shared`,
        '  helper rather than leaving the duplicate behind.',
        '',
        `  ${dim('Edited')} ${cyan('lib/billing/refunds.ts')}  ${green('+6')} ${red('-19')}`,
        '',
        `  ${dim('Churned for 38s · done 11:46')}`,
        '',
        `  ${dim('›')} ${dim('▏')}`,
        '',
        `  ${dim('bypass permissions on (shift+tab to cycle) · ← for agents')}                                   ${dim('/rc')}`,
    ),
    'demo-upload': lines(
        '',
        `  ${bold('The thumbnail test fails maybe one run in five on CI but never locally.')}`,
        '',
        `  ${dim('Read')} ${cyan('tests/upload.spec.ts')} ${dim('· 140 lines')}`,
        `  ${dim('Ran')} ${cyan('pnpm test upload --repeat 40')}`,
        `  ${red('✗')} 6 of 40 runs failed ${dim('— all on "generates a thumbnail"')}`,
        '',
        '  It is not flaky infrastructure. The upload resolves as soon as the object lands in storage,',
        `  but the thumbnail job is queued separately, so the assertion races the worker.`,
        '',
        `  Which behaviour do you actually want? ${yellow('This changes the API contract, so I stopped here.')}`,
        '',
        `    ${yellow('1.')} Upload waits for the thumbnail — slower, but a 200 means the asset is complete.`,
        `    ${yellow('2.')} Upload returns immediately and the thumbnail arrives later ${dim('(current intent)')}.`,
        '',
        `  If it is 2, the test is wrong rather than the code, and I will make it poll the asset.`,
        '',
        `  ${dim('Waiting for you · 18m')}`,
        '',
        `  ${dim('›')} ${dim('▏')}`,
    ),
    'demo-ratelimit': lines(
        '',
        `  ${bold('Add a token bucket to /search before we open it to the public API.')}`,
        '',
        `  ${dim('Read')} ${cyan('src/routes/search.ts')} ${dim('· 88 lines')}`,
        `  ${dim('Read')} ${cyan('src/middleware/auth.ts')} ${dim('· 61 lines')}`,
        `  ${dim('Grep')} ${cyan('"rateLimit"')} ${dim('· 3 matches')}`,
        '',
        `  There is already a bucket in ${cyan('src/middleware/quota.ts')} used by the upload routes, so this`,
        '  should reuse it rather than introduce a second implementation. Checking whether it keys on',
        `  the API key or the account before I wire it in${blue('…')}`,
        '',
    ),
    'demo-config': lines(
        '',
        `  ${bold('Every env var is read inline all over the app. Give me one validated config.')}`,
        '',
        `  ${dim('Grep')} ${cyan('"process.env"')} ${dim('· 19 matches across 12 files')}`,
        `  ${dim('Edited')} ${cyan('lib/config.ts')}  ${green('+64')} ${red('-0')}`,
        `  ${dim('Edited')} ${dim('11 call sites')}  ${green('+23')} ${red('-31')}`,
        '',
        `  All 19 reads go through ${cyan('config')} now, parsed once at boot. A missing ${cyan('STRIPE_KEY')} fails`,
        '  immediately with the variable named, instead of surfacing as undefined during a checkout.',
        '',
        `  ${dim('Ran')} ${cyan('pnpm typecheck')}  ${green('✓')} ${dim('no errors')}`,
        '',
        `  ${dim('Brewed for 4m 02s · done 08:15')}`,
        '',
        `  ${dim('›')} ${dim('▏')}`,
    ),
    'demo-shell': lines(
        `${dim('~/code/storefront')} ${cyan('main')} $ pnpm test --filter web`,
        '',
        `${green('✓')} src/cart/cart.test.ts ${dim('(18 tests)')}`,
        `${green('✓')} src/checkout/summary.test.tsx ${dim('(9 tests)')}`,
        `${green('✓')} lib/pricing/totals.test.ts ${dim('(24 tests)')}`,
        '',
        `${dim('Test Files')}  3 passed ${dim('(3)')}`,
        `${dim('     Tests')}  51 passed ${dim('(51)')}`,
        `${dim('  Duration')}  2.41s`,
        '',
        `${dim('~/code/storefront')} ${cyan('main')} $ `,
    ),
};

export function transcriptFor(viewId: string): TranscriptChunk[] {
    const transcript = TRANSCRIPTS[viewId];
    if (!transcript) return [];
    const last = transcript.at(-1)!;
    return [
        { text: '\x1b[?25l', delay: 0 },
        ...transcript.slice(0, -1),
        { ...last, text: last.text.replace(/\r\n$/, '') },
    ];
}
